# .github/workflows/deploy.yml
name: Deploy Nuxt.js to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Nuxt.js Static Site
        run: npm run generate

      # NUEVO PASO: Sube el artefacto generado por Nuxt para el despliegue de Pages
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # *** IMPORTANTE: AJUSTA ESTA RUTA SI TU CARPETA DE SALIDA ES DIFERENTE ***
          path: ./.output/public # La carpeta donde 'npm run generate' pone los archivos estáticos

      # Desplegar el sitio generado a GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4